[phases.setup]
cmds = [
  '''
  INI_DIR=$(find /nix/store/*-php-*/lib -name php.ini -print0 | head -z -n 1 | rev | cut -c 9- | rev)
  echo "upload_max_filesize=100M;" >> "$INI_DIR/upload.ini"
  echo "post_max_size=100M;" >> "$INI_DIR/upload.ini"
  '''
]
